#!/usr/bin/env python3
"""Regenerate assets/tree.js from the folder tree — the sidebar index.

The filesystem IS the page tree: a *page* is any folder containing index.html.
Its children are immediate sub-folders that themselves contain index.html
(so figures/ data/ scripts/ assets/ are skipped automatically — they have none).
Page title = the page's <h1> text (falls back to <title>, then the folder name).

This is a read-of-disk → write-one-file step, not a site build: pages render fine
on their own; tree.js only feeds the sidebar. Run after adding/moving pages:

    python3 gen-tree.py
"""
from __future__ import annotations
import html
import json
import re
from pathlib import Path

SITE = Path(__file__).resolve().parent
RESERVED = {"assets", "figures", "data", "scripts"}


def title_of(index_html: Path, fallback: str) -> str:
    text = index_html.read_text(encoding="utf-8", errors="ignore")
    m = re.search(r"<h1[^>]*>(.*?)</h1>", text, re.S | re.I) or \
        re.search(r"<title[^>]*>(.*?)</title>", text, re.S | re.I)
    if not m:
        return fallback
    inner = re.sub(r'<span[^>]*class="[^"]*status[^"]*"[^>]*>.*?</span>', "", m.group(1), flags=re.S | re.I)
    raw = re.sub(r"<[^>]+>", "", inner)               # drop the status pill, then strip remaining tags
    raw = re.sub(r"\s+", " ", html.unescape(raw)).strip()
    return raw or fallback


def _natkey(p: Path):
    # Natural order so 2-method/ sorts before 10-summary/ (not lexicographic 10<2).
    return [int(t) if t.isdigit() else t.lower() for t in re.split(r"(\d+)", p.name)]


def node(folder: Path) -> dict:
    rel = folder.relative_to(SITE).as_posix()
    path = "index.html" if rel == "." else f"{rel}/index.html"
    children = []
    subs = (p for p in folder.iterdir() if p.is_dir() and p.name not in RESERVED)
    for sub in sorted(subs, key=_natkey):
        if (sub / "index.html").exists():
            children.append(node(sub))
    return {"title": title_of(folder / "index.html", folder.name), "path": path, "children": children}


def main() -> None:
    tree = node(SITE)
    body = json.dumps(tree, ensure_ascii=False, indent=2)
    (SITE / "assets" / "tree.js").write_text(
        "/* AUTO-GENERATED by gen-tree.py — do not hand-edit unless you mean to. */\n"
        f"window.SITE_TREE = {body};\n",
        encoding="utf-8",
    )
    n = 0
    def count(x):
        nonlocal n; n += 1; [count(c) for c in x["children"]]
    count(tree)
    print(f"wrote assets/tree.js — {n} pages")


if __name__ == "__main__":
    main()
