#!/usr/bin/env python3
"""Regenerate assets/tree.js from the folder tree — the sidebar index.

The filesystem IS the page tree: a *page* is any folder containing index.html.
Its children are immediate sub-folders that themselves contain index.html
(so figures/ data/ scripts/ assets/ are skipped automatically — they have none).
Page title = the page's <h1> text (falls back to <title>, then the folder name).

This is a read-of-disk → write-one-file step, not a site build: pages render fine
on their own; tree.js only feeds the sidebar. Run after adding/moving pages:

    python3 gen-tree.py
"""
from __future__ import annotations
import html
import json
import re
from pathlib import Path

SITE = Path(__file__).resolve().parent
RESERVED = {"assets", "figures", "data", "scripts"}

# Output folders listed at the bottom of each page, viewable in a modal.
OUT_DIRS = ("figures", "data", "scripts")
IMG_EXT = {".png", ".svg", ".jpg", ".jpeg", ".gif", ".webp", ".avif"}
TEXT_EXT = {".py", ".sh", ".txt", ".csv", ".tsv", ".md", ".json", ".yaml", ".yml",
            ".in", ".out", ".log", ".toml", ".cfg", ".ini", ".dat", ".gnu", ".pl",
            ".f90", ".c", ".cpp", ".h", ".tex", ".bib", ".m", ".jl", ".r", ".xml"}
TEXT_CAP = 256 * 1024  # embed text up to this size; larger -> open-link only


def _file_entry(f: Path, page_dir: Path) -> dict:
    ext = f.suffix.lower()
    e = {"name": f.name, "path": f.relative_to(page_dir).as_posix(), "size": f.stat().st_size}
    if ext in IMG_EXT:
        e["kind"] = "img"
    elif ext in TEXT_EXT and e["size"] <= TEXT_CAP:
        try:
            e["content"] = f.read_text(encoding="utf-8")
            e["kind"] = "text"
        except (UnicodeDecodeError, OSError):
            e["kind"] = "link"
    else:
        e["kind"] = "link"
    return e


def write_files_js(page_dir: Path) -> bool:
    """Write {page}/files.js (window.PAGE_FILES) listing its output files, with
    small text contents embedded so the viewer modal needs no fetch (file://-safe)."""
    groups = {}
    for d in OUT_DIRS:
        sub = page_dir / d
        if not sub.is_dir():
            continue
        files = sorted((p for p in sub.rglob("*") if p.is_file()), key=_natkey)
        if files:
            groups[d] = [_file_entry(p, page_dir) for p in files]
    fjs = page_dir / "files.js"
    if groups:
        fjs.write_text("window.PAGE_FILES = " + json.dumps(groups, ensure_ascii=False) + ";\n",
                       encoding="utf-8")
        return True
    if fjs.exists():
        fjs.unlink()  # stale: page no longer has outputs
    return False


def title_of(index_html: Path, fallback: str) -> str:
    text = index_html.read_text(encoding="utf-8", errors="ignore")
    m = re.search(r"<h1[^>]*>(.*?)</h1>", text, re.S | re.I) or \
        re.search(r"<title[^>]*>(.*?)</title>", text, re.S | re.I)
    if not m:
        return fallback
    inner = re.sub(r'<span[^>]*class="[^"]*status[^"]*"[^>]*>.*?</span>', "", m.group(1), flags=re.S | re.I)
    raw = re.sub(r"<[^>]+>", "", inner)               # drop the status pill, then strip remaining tags
    raw = re.sub(r"\s+", " ", html.unescape(raw)).strip()
    return raw or fallback


def _natkey(p: Path):
    # Natural order so 2-method/ sorts before 10-summary/ (not lexicographic 10<2).
    return [int(t) if t.isdigit() else t.lower() for t in re.split(r"(\d+)", p.name)]


def node(folder: Path, counters: dict) -> dict:
    rel = folder.relative_to(SITE).as_posix()
    path = "index.html" if rel == "." else f"{rel}/index.html"
    counters["pages"] += 1
    if write_files_js(folder):
        counters["files_js"] += 1
    children = []
    subs = (p for p in folder.iterdir() if p.is_dir() and p.name not in RESERVED)
    for sub in sorted(subs, key=_natkey):
        if (sub / "index.html").exists():
            children.append(node(sub, counters))
    return {"title": title_of(folder / "index.html", folder.name), "path": path, "children": children}


def main() -> None:
    counters = {"pages": 0, "files_js": 0}
    tree = node(SITE, counters)
    body = json.dumps(tree, ensure_ascii=False, indent=2)
    (SITE / "assets" / "tree.js").write_text(
        "/* AUTO-GENERATED by gen-tree.py — do not hand-edit unless you mean to. */\n"
        f"window.SITE_TREE = {body};\n",
        encoding="utf-8",
    )
    print(f"wrote assets/tree.js — {counters['pages']} pages, "
          f"{counters['files_js']} files.js")


if __name__ == "__main__":
    main()
